spring:
  application:
    name: Locacoes Web
  jpa:
    show-sql: true
    properties:
      hibernate:
        default_schema: locacoes-web
  generate-ddl: true
  hibernate:
    ddl-auto: validate
  open-in-view: true

  datasource:
    url: jdbc:mysql://localhost:3307/locacoes-web
    username: root
    password: locacoes123
    driver-class-name: com.mysql.cj.jdbc.Driver

flyway:
  enabled: true
  baseline-on-migrate: true

server:
  port: 8081